config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_jobs, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @jobs = Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)
    if @job.save
      redirect_to @job
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render "edit"
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url, :category_id)
  end

  def find_jobs
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: "form-horizontal" }) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}, input_html: {class: "dropdown-toggle"}
  = f.input :title, label: "Заголовок работы", input_html: {class: "form-control"}
  = f.input :description, label: "Описание", input_html: {class: "form-control"}
  = f.input :company, label: "Ваша компания", input_html: {class: "form-control"}
  = f.input :url, label: "Ссылка на работу", input_html: {class: "form-control"}
  %br/
  = f.button :submit

app/views/jobs/edit.html.haml
%h1 Изменить

= render 'form'

= link_to "Назад", root_path

app/views/jobs/index.html.haml
#jobs
  - @jobs.each do |job|
    .job
      %h2= link_to job.title, job
      %p= job.company

app/views/jobs/new.html.haml
%h1 Создать

= render 'form'

= link_to "Назад", root_path

app/views/jobs/show.html.haml
#jobs
  .job
    %h2= @job.title
    %p= @job.description
    %p= @job.company
    %button.btn.btn-default= link_to "Подтвердить", @job.url

#links
  = link_to "Назад", root_path, class: "btn btn-sm btn-default"
  = link_to "Изменить", edit_job_path(@job), class: "btn btn-sm btn-default"
  = link_to "Удалить", job_path(@job), method: :delete, data: {confirm: "Вы уверены?"}, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'true'
  %body
    %nav.navbar.navbar-default
      .container
        = link_to "Ruby Работа", root_path, class: "navbar-brand"
        %ul.nav.navbar-nav
          %li= link_to "Все вакансии", root_path
          - Category.all.each do |category|
            %li= link_to category.name, jobs_path(category: category.name)
        = link_to "Новая работа", new_job_path, class: "navbar-text navbar-right navbar-link"
    .container
      .col-md-6.col-md-offset-3
        = yield